#!/bin/bash

IP_ADDR=130.58.68.194
LOCATION='cs87/Project-ldouhov1-scasada1-ylala1/source/client_tracker'
SCRIPT="./"$LOCATION"/bin/client -i $IP_ADDR -f "$LOCATION"/test_scripts/test_data/aot.sly -s "$LOCATION"/test_scripts/test_data/aot"

  COMMAND="pkill -u scasada1"

  MACHINES=(
    "mew"
    "abra"
    "beedrill"
    "bulbasaur"
    "butterfree"
    "charmander"
    "clefairy"
    "diglett"
    "ditto"
    "dratini"
    "eevee"
    "ekans"
    "gastly"
    "geodude"
    "horsea"
    "koffing"
    "mankey"
    "meowth"
    "oddish"
    "onix"
    "pidgey"
    "pikachu"
    "poliwag"
    "ponyta"
    "psyduck"
    "rattata"
    "seel"
    "jigglypuff"
    "snorlax"
    "squirtle"
    "staryu"
    "carrot"
    "mustard"
    "mace"
    "cornstarch"
    "poppy"
    "bacon"
    "caper"
    "onion"
    "honey"
    "cream"
    "nutmeg"
    "coriander"
    "mugwort"
    "cheese"
    "celery"
    "oil"
    "oregano"
    "thyme"
    "rosemary"
    "tomato"
    "flour"
    "lime"
    "sage"
    "turmeric"
    "butter"
    "horseradish"
    "pimento"
    "owl"
    "hawk"
    "pelican"
    "pigeon"
    "puffin"
    "quail"
    "raven"
    "grebe"
    "seagull"
    "sparrow"
    "myrtle"
    "oriole"
    "macaw"
    "magpie"
    "swan"
    "loon"
    "lark"
    "kestrel"
    "ibis"
    "wren"
    "grouse"
    "flamingo"
    "finch"
    "falcon"
    "egret"
    "eagle"
    "dodo"
    "cuckoo"
    "crane"
    "cardinal"
    "heron"
    "buzzard"
    "ostrich"
    "bluejay"

    #"growlithe"
    #"pepper"
    #"spinach"
    #"cabbage"
  )

  for machine in ${MACHINES[@]}; do
    ssh scasada1@$machine $COMMAND > /dev/null 2>&1 & 
  done
  
  exit 0


